In [269]:
import numpy as np

In [270]:
def describe_array(array):
    print(array)
    print("clase: "+str(type(array)))
    print("elementos: "+str(len(array)))
    print("columnas x filas: "+str(array.shape))
    print("dimensiones: "+str(array.ndim))
    print("tipo de dato: "+str(array.dtype))

In [271]:
# 1D array of 5 elements of type float32
x = np.array([1, 2, 3, 4, 5], dtype=np.float32)
describe_array(x)

[1. 2. 3. 4. 5.]
clase: <class 'numpy.ndarray'>
elementos: 5
columnas x filas: (5,)
dimensiones: 1
tipo de dato: float32


In [272]:
y = np.array([[1, 2, 3,], [4, 5, 6]])
# 2 formas de cambiar entre columnas y filas
y.shape = (3, 2)
describe_array(y)

[[1 2]
 [3 4]
 [5 6]]
clase: <class 'numpy.ndarray'>
elementos: 3
columnas x filas: (3, 2)
dimensiones: 2
tipo de dato: int32


In [273]:
y = y.reshape(2, 3)
describe_array(y)

[[1 2 3]
 [4 5 6]]
clase: <class 'numpy.ndarray'>
elementos: 2
columnas x filas: (2, 3)
dimensiones: 2
tipo de dato: int32


In [274]:
z = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
# se puede acceder a los elementos de un array de la siguiente forma 
print(z[0, 1])
# o de esta otra forma como con un array normal
print(z[0][1])

# se puede acceder a un rango de elementos de las siguientes formas
print(z[0:3, 2:3]) # de la fila 0 a la 3 y de la columna 2 a la 3
print("------------")
print(z[0:2, 2]) # de la fila 0 a la 2 y de la columna 2
print("------------")
print(z[[1,2],2]) # de la fila 0 y 2 y de la columna 2
print("------------")

2
2
[[3]
 [6]
 [9]]
------------
[3 6]
------------
[6 9]
------------


In [275]:
# prueba de intercambiar la fila 0 por la 1
print(z[[1,0,2],:])

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [276]:
# crear un array de 0s
zeros = np.zeros((3, 4))
describe_array(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
clase: <class 'numpy.ndarray'>
elementos: 3
columnas x filas: (3, 4)
dimensiones: 2
tipo de dato: float64


In [277]:
# crear un array de 1s
unos = np.ones((3, 4))
describe_array(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
clase: <class 'numpy.ndarray'>
elementos: 3
columnas x filas: (3, 4)
dimensiones: 2
tipo de dato: float64


In [278]:
# crear un array de un numero concreto e int32
numeros = np.full((3, 4), 5, dtype=np.int32)
describe_array(numeros)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
clase: <class 'numpy.ndarray'>
elementos: 3
columnas x filas: (3, 4)
dimensiones: 2
tipo de dato: int32


In [279]:
# cambiar el tipo del array ya creado
numeros = numeros.astype(np.float32)
describe_array(numeros)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
clase: <class 'numpy.ndarray'>
elementos: 3
columnas x filas: (3, 4)
dimensiones: 2
tipo de dato: float32


In [280]:
# crear una matriz de identidad de 3x3 https://es.wikipedia.org/wiki/Matriz_identidad
prueba = np.eye(3)
describe_array(prueba)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
clase: <class 'numpy.ndarray'>
elementos: 3
columnas x filas: (3, 3)
dimensiones: 2
tipo de dato: float64


In [281]:
# crear un array de con numeros diferentes por la diagonal
prueba = np.diag([1, 2, 3, 4])
describe_array(prueba)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
clase: <class 'numpy.ndarray'>
elementos: 4
columnas x filas: (4, 4)
dimensiones: 2
tipo de dato: int32


In [282]:
# crear un array con numeros del 10 al 20 con saltos de 2
arange = np.arange(10,20,2)
describe_array(arange)

[10 12 14 16 18]
clase: <class 'numpy.ndarray'>
elementos: 5
columnas x filas: (5,)
dimensiones: 1
tipo de dato: int32


In [283]:
# crear un array con numeros de igual espacio entre ellos
linspace = np.linspace(0, 1, 5)
describe_array(linspace)

[0.   0.25 0.5  0.75 1.  ]
clase: <class 'numpy.ndarray'>
elementos: 5
columnas x filas: (5,)
dimensiones: 1
tipo de dato: float64


In [317]:
# crear un numero aleatorio
np.random.seed(42)
random = np.random.randint(10)
print(random)

6


In [318]:
# crear un array de numeros aleatorios
random = np.random.randint(1,50, size=(3, 4))
describe_array(random)

[[29 15 43  8]
 [21 39 19 23]
 [11 11 24 36]]
clase: <class 'numpy.ndarray'>
elementos: 3
columnas x filas: (3, 4)
dimensiones: 2
tipo de dato: int32


In [321]:
# crear un array de numeros aleatorios 
random = np.random.random(size=10)
describe_array(random)

[0.46676289 0.85994041 0.68030754 0.45049925 0.01326496 0.94220176
 0.56328822 0.3854165  0.01596625 0.23089383]
clase: <class 'numpy.ndarray'>
elementos: 10
columnas x filas: (10,)
dimensiones: 1
tipo de dato: float64


In [323]:
# crear un array de numeros aleatorios uniformes
random_uniform = np.random.uniform(1, 100, size=10)
describe_array(random_uniform)

[57.20233245  4.10001595 84.38619268 45.5256592  40.11987336 92.73922771
 72.99992759 33.32753611 57.47395347 52.56259174]
clase: <class 'numpy.ndarray'>
elementos: 10
columnas x filas: (10,)
dimensiones: 1
tipo de dato: float64


In [327]:
# crear un array de numeros aleatorios con distribucion normal
media = 1.70
desviacion = 0.1
random_normal = np.random.normal(media, desviacion, size=100)
describe_array(random_normal)

[1.79648106 1.59351688 1.71087118 1.71057636 1.79206667 1.67732775
 1.76530483 1.81026875 1.51501971 1.81686312 1.60146182 1.59060596
 1.41205431 1.61968223 1.69951431 1.66166767 1.65374731 1.58875026
 1.78672295 1.79584138 1.74181185 1.5113472  1.92733452 1.71469747
 1.75396092 1.55017044 1.69885566 1.74133541 1.68591014 1.78721619
 1.83003451 1.56564762 1.78501206 1.739434   1.6995304  1.5429188
 1.84798488 1.73967743 1.52167489 1.67568655 1.73272234 1.75065753
 1.68723952 1.73415908 1.91188862 1.85465368 1.6050481  1.64031027
 1.6888796  1.52509306 1.56585965 1.53783054 1.585228   1.83896028
 1.61447595 1.59729382 1.78828377 1.65506956 1.74186395 1.62718208
 1.5198112  1.74677171 1.54485661 1.64895068 1.62670489 1.71953465
 1.64440551 1.68722652 1.54394429 1.90003481 1.57998683 1.82013804
 1.71498337 1.71409074 1.73544196 1.51196874 1.7966392  1.64890555
 1.82103986 1.6848764  1.66254784 1.57087839 1.62344906 1.74223138
 1.56920857 1.50094005 1.61424511 1.78400054 1.87812911 1.63225

In [328]:
print("media: "+str(np.mean(random_normal)))

media: 1.6872123529990335


In [329]:
print("desviacion: "+str(np.std(random_normal)))

desviacion: 0.10803560448899031


In [330]:
print("mediana: "+str(np.median(random_normal)))

mediana: 1.6880595602954176


In [334]:
# crear un array de caras y cruzes de monedas
monedas = np.random.choice(["cara", "cruz"], size=100)
describe_array(monedas)

['cara' 'cruz' 'cruz' 'cruz' 'cara' 'cara' 'cruz' 'cara' 'cruz' 'cara'
 'cruz' 'cruz' 'cara' 'cruz' 'cara' 'cruz' 'cruz' 'cara' 'cara' 'cara'
 'cruz' 'cara' 'cruz' 'cruz' 'cara' 'cara' 'cruz' 'cruz' 'cara' 'cara'
 'cara' 'cara' 'cara' 'cruz' 'cruz' 'cruz' 'cruz' 'cara' 'cara' 'cara'
 'cruz' 'cruz' 'cara' 'cara' 'cruz' 'cruz' 'cara' 'cara' 'cruz' 'cara'
 'cara' 'cara' 'cruz' 'cruz' 'cruz' 'cruz' 'cruz' 'cruz' 'cruz' 'cara'
 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cruz' 'cruz' 'cara' 'cara'
 'cruz' 'cara' 'cara' 'cruz' 'cara' 'cruz' 'cara' 'cruz' 'cruz' 'cruz'
 'cara' 'cruz' 'cara' 'cara' 'cara' 'cara' 'cruz' 'cruz' 'cara' 'cara'
 'cruz' 'cara' 'cruz' 'cara' 'cara' 'cruz' 'cara' 'cruz' 'cara' 'cara']
clase: <class 'numpy.ndarray'>
elementos: 100
columnas x filas: (100,)
dimensiones: 1
tipo de dato: <U4


In [359]:
# contar el numero de caras 
print("cara: "+str(sum(monedas == "cara")))

cara: 73


In [356]:
# crear un array de cara y cruz con moneda trucada para que salga cara 70% de las veces
monedas = np.random.choice(["cara", "cruz"], size=100, p=[0.7, 0.3])
describe_array(monedas)

['cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara'
 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cruz' 'cara' 'cara' 'cruz'
 'cruz' 'cruz' 'cruz' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara'
 'cruz' 'cruz' 'cara' 'cruz' 'cara' 'cruz' 'cara' 'cruz' 'cara' 'cara'
 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cruz' 'cara' 'cara'
 'cara' 'cruz' 'cara' 'cruz' 'cruz' 'cara' 'cara' 'cruz' 'cruz' 'cara'
 'cara' 'cruz' 'cara' 'cruz' 'cara' 'cara' 'cruz' 'cara' 'cara' 'cara'
 'cara' 'cara' 'cara' 'cara' 'cruz' 'cara' 'cara' 'cara' 'cruz' 'cruz'
 'cara' 'cara' 'cara' 'cruz' 'cruz' 'cara' 'cruz' 'cruz' 'cara' 'cara'
 'cara' 'cara' 'cruz' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara' 'cara']
clase: <class 'numpy.ndarray'>
elementos: 100
columnas x filas: (100,)
dimensiones: 1
tipo de dato: <U4


In [360]:
# contar el numero de caras 
print("cara: "+str(sum(monedas == "cara")))

cara: 73


In [369]:
# mostrar maximos y minimos del array
array = np.random.randint(1,50, size=5)
print(array)
print("maximo: "+str(np.max(array)))
print("minimo: "+str(np.min(array)))

[13 49  2  5 44]
maximo: 49
minimo: 2


In [370]:
# mostrar maximos y minimos del array por filas y columnas
array = np.random.randint(1,50, size=(3, 4))
print(array)
print("maximo: "+str(np.max(array, axis=0)))
print("minimo: "+str(np.min(array, axis=1)))

[[27 32 21  8]
 [38  8  3 44]
 [ 3 22  6  2]]
maximo: [38 32 21 44]
minimo: [8 3 2]


In [391]:
# mostrar el valor maximo y minimo del array por filas y columnas
array = np.random.randint(1,50, size=10)
print(array)
index = np.argmax(array, axis=0)
print("maximo: "+str(array[index]))


[32 36 17 35 49 11 21 26  4 34]
maximo: 49


In [394]:
# crear 2 arrays y unirlos en uno verticalmente
array1 = np.random.randint(1,50, size=5)
array2 = np.random.randint(1,50, size=5)
array3 = np.vstack((array1, array2))
describe_array(array3)

[[29 33 10 40 21]
 [28 11 34  8 22]]
clase: <class 'numpy.ndarray'>
elementos: 2
columnas x filas: (2, 5)
dimensiones: 2
tipo de dato: int32


In [405]:
# comprobar una condición sobre los elementos de un array y devolver un array de booleanos
array = np.arange(1,10)
print(array)

mayores_4 = array > 4
print(mayores_4)

[1 2 3 4 5 6 7 8 9]
[False False False False  True  True  True  True  True]


In [406]:
print(array[mayores_4])

[5 6 7 8 9]
